### ISSUE TITLE
linuxthefish isn't included in the statistics

### ISSUE THREAD

**Issue by linuxthefish** [Southclaws/cj#102]
Hello,

When the statistics for the SA-MP server appear, the username of linuxthefish isn't included. This user has posted many messages, and so should be included in the statistics.

Please fix this ASAP, thanks. 
![image](https://user-images.githubusercontent.com/7034072/50048588-2d00d800-00c8-11e9-84f1-7199dd20dac1.png)

**Comment by Southclaws** [comment]
Hi,

My name is Southclaws and I'll be assisting you today. According to our records you have posted 13,314 messages at the time of this writing. Unfortunately this is not enough to appear in the top 10 list. Please post more messages to appear in the top 10 list.

Have a great day!

Thanks

**Comment by linuxthefish** [comment]
:angry:

**Comment by linuxthefish** [comment]
test
