### ISSUE TITLE
Move verification to burgershot.

### ISSUE THREAD

**Issue by J0shES** [Southclaws/cj#112]
How should already verified users be handled? @Southclaws 

Specifically for stuff like /whois /userinfo

**Comment by J0shES** [comment]
Well, I figured out a solution thanks to @ADRFranklin :

There will be two types of verified, 'LegacyVerified' (SA:MP) and 'Verified' (in the code - not dependent on server roles). Legacy verified can be /whois'd but cannot be /userinfo'd due to obvious reasons of CJ being IP blocked.

Legacy verified people can message CJ with 'reverify' and CJ will then do the verify process again in which they will be set to 'Verified'.

**Comment by Crayder** [comment]
I think they should keep the Legacy role as well, just as a little extra proof for those skeptical of who someone is and their origin.

**Comment by J0shES** [comment]
There's no role associated with it, 'Legacy' is really a term in the code.

**Comment by Southclaws** [comment]
Yes, the existing `verified` role will remain and CJ's database will maintain the links between verified users and their existing SA:MP Forums account.

The new verified role will be a new link in the DB and a new role.

**Comment by J0shES** [comment]
#113
