### ISSUE TITLE
No way to get verified role if already verified but without role

### ISSUE THREAD

**Issue by AdamsLT** [Southclaws/cj#115]
Today CJ was updated several times, during which my account roles bugged out.

I verified my account on the burgershot.gg forums. 
Then, I believe, the verified role was deleted for everyone and recreated.
I was removed from the role but I remained verified on the forum during that time.

The problem: now I can't get my verified role back on discord, because CJ already tells me I'm verified but doesn't assign the missing role to me.

![Image of CJ's DMs](https://i.imgur.com/EqAfMsN.png)

![Image of my roles](https://i.imgur.com/aQhh5vq.png)

Suggestion to fix: if I'm already verified and PM CJ "verify" I would still receive the message that I'm verified but also CJ should check my role and assign it if it's missing.

P.S. If a user is verified and tries to verify again, CJ should only send the message that you're verified (in the image you can see that CJ sends two messaged, of which 1 isn't needed)

**Comment by Southclaws** [comment]
I figured this would happen to at least one person! During boot, CJ runs through every user and makes sure their role represents what's present in the DB. The thing is, when the changes were made, the `IsUserVerified` returned false for every user, which resulted in CJ removing the verified role from everyone - you were just unlucky enough to get hit at the wrong time.

This shouldn't happen again, though if I remember some time, I'll fix it. (done enough code today!)
