### ISSUE TITLE
[/impersonate] command 

### ISSUE THREAD

**Issue by somillgumber** [Southclaws/cj#127]
So while having fun with CJ, I had some problem using [/impersonate] command. So basically, we use this command like this [/impersonate Somil] then there are times when there are two people with same name and then CJ bot don't even responds to it.

**Comment by J0shES** [comment]
/quote is designed to not take any parameters by the user at all.
Maybe you're referring to /impersonate?

**Comment by somillgumber** [comment]
Sorry, fixed it

**Comment by Southclaws** [comment]
#128 may resolve this by completely removing these commands.

**Comment by somillgumber** [comment]
Thanks :)
