### ISSUE TITLE
Commands as classes

### ISSUE THREAD

**Issue by WopsS** [Southclaws/cj#13]
We should organize all commands on classes and handle them dynamically in a function when a message is received. For example every command class should be like this
```golang
type CommandName struct {}

func (c *CommandName) Name() string {
	return "command_name"
}

func (c *CommandName) Description() string {
	return "description"
}

func (c *CommandName) Usage() string {
	return "usage"
}

func (c *PollCommand) Process() {
}
```

**Comment by Southclaws** [comment]
I'm partially for this but have some questions:

What do you mean by dynamically call? As far as I know, there's no clean way to simply call a function by string-name, we'd have to map them somewhere - which isn't a problem, we're only going to have a small amount of commands, around 10 and probably never more than 30 so a simple map in a `bot_commands.go` file could deal with this.

I might play around with some ideas and see, I am definitely down for having each command in its own file it's just dependent on the best way to deal with the composition of classes.

**Comment by WopsS** [comment]
> What do you mean by dynamically call?
Sincerely I was thinking about something like C#
```csharp
typeof(MyType).GetMethod("add").Invoke(null, new [] {arg1, arg2})
```
or PHP. I don't know about **Go** I'm working in it for about 12 hours 😆, but I saw something with **reflect**.

**Comment by Southclaws** [comment]
Yeah it's not really a Go thing to call functions by string name - Go is closer to C.

But still, we can store a map of commands to functions:

```go
map[string]string{
    "verify": commandVerify,
}
```

And more likely, expand that to an Object:

```go
map[string]string{
    "verify": Command{funcCall: app.commandVerify, Enabled: true},
}
```

Which is fine, it also gives us the ability to enable/disable or do other things with Command objects.

**Comment by WopsS** [comment]
Same as #18.
