### ISSUE TITLE
Random quotes

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#14]
Since the bot is logging all chat, a common IRC feature will be easy to implement: random quote from a user from the past. These kinds of things should be on a cooldown or require some kind of currency to use however to prevent spam.

**Comment by WopsS** [comment]
Should this be hard-coded or get them from database and add them to database with a command (**/addquote [text]**)?

**Comment by Southclaws** [comment]
No need to add quotes manually, the bot is already logging every chat message from every channel (may need to minimise this to just the primary channel or ignore the admin channel soon, but that's another issue) so all that needs to happen is a query by username to the chat log table and pick a random entry. Should be possible with a single query and could be deferred to a goroutine if performance becomes an issue. SQLite should be fine for this job for now though.

**Comment by WopsS** [comment]
But what if that random entry is "Hello"? Should we send it?

**Comment by Southclaws** [comment]
We could count words (or other metrics) and only send messages marked as "interesting".

**Comment by Crayder** [comment]
What if we count a specific reaction as interesting? It would only count for admins who reacted with it. Use something random like :cake:.

If an admin reacts with :cake: then that message will be considered interesting.

**Comment by Southclaws** [comment]
I'd prefer it to be automatic, we can use other metrics anyway. I didn't mean interesting from a semantic point of view, I just meant in terms of whether or not the message is worth reposting in response to what WopsS said about the message possibly being a single word.

**Comment by Crayder** [comment]
He could also do a set of his own quotes, like from [here](http://www.imdb.com/character/ch0019114/quotes). That would be a pretty dope side features. We could take all of the more general quotes from that page, all of the ones that aren't directed at a specific person or anything like that. So like, we could take all of the quotes where he's stealing cars and stuff.
