### ISSUE TITLE
CJ responds to mention in primary channel even when mentioned in a different channel

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [Southclaws/cj#167]
Mentioning CJ in the #software-dev channel light up his 'typing' status: 

![ôfbylding](https://user-images.githubusercontent.com/15870306/82451919-e7abbb80-9aae-11ea-9e7d-adf75ba7eac0.png)

But he ends up posting in his primary channel:

![ôfbylding](https://user-images.githubusercontent.com/15870306/82451969-fb572200-9aae-11ea-81b0-2a04b038b347.png)

It's unclear to me what the expected behavior is: should CJ not reply to a mention outside the primary channel or should be reply but in the right channel?

**Comment by Southclaws** [comment]
The "primary channel" concept is very outdated, it was from a time where the discord had very few channels and CJ didn't do much. This was mostly changed when per-command runtime config was added but a few commands still had the old legacy channel types as target channels for output.

**Comment by NotUnlikeTheWaves** [comment]
Maybe it's an idea to make this a general refactor point and remove the primary channel altogether. Are the other designated channels (e.g. helper channel) also outdated?

**Comment by Southclaws** [comment]
That's probably best. From what I remember, there was one reason the code was kept but it's probably something that can be removed anyway.

**Comment by coool9** [comment]
Isn't this fixed? CJ responds anywhere now.
