### ISSUE TITLE
Count user's message reactions

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#17]
We all know whoever posts the spiciest meme gets the most reactions. Let's count them.

Since there isn't a gateway event for reaction creation (as far as I can see) this one will need to be a polling function that grabs the last X messages and counts reactions for them and distributes the score to the relevant users.

**Comment by Crayder** [comment]
Counting `:rep:` and `:thumbsdown:/:thumbsup:` should be great!

**Comment by Southclaws** [comment]
I had some thoughts about an efficient way to do this with minimal polling and caching. Since there's no "react" gateway event as far as I know this is going to have to be manual and it's going to have some threshold of how long after a message has been created it stops being counted for reactions. From looking at general conversation, it seems about a 10 second window for messages should be fine, and we don't need to be super accurate with this sort of stuff - records can be fuzzy as I doubt users are keeping tally!

Now, on to how it could work:

Each message that comes in can have its message ID stored in a growing queue, every X seconds, *all* the items in this queue can have their reactions counted but only *half* of the items at the front of the queue are popped off (the oldest items).

This way, we have an overlapping, moving window across the dataset that ensures each message is checked twice during the window (this method has a name, I forgot it!)

I'll do a mock up of this once I've finished working on #18 

(I've also removed the 'easy' tag from this as I realise it's going to need a bit more thought)

**Comment by J0shES** [comment]
I was thinking about a fun and simple little reputation system that could be used with the :rep: emote we have.

**Comment by Southclaws** [comment]
That would be cool, I guess I completely forgot about this feature!

**Comment by NotUnlikeTheWaves** [comment]
Closed! This can be accessed via `/rep [optional: emoji]`. Defaults to the emoji set in the config
