### ISSUE TITLE
Define a framework for commands

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#18]

**Comment by Southclaws** [comment]
```go
// LoadCommands is called on initialisation and is responsible for registering
// all commands and binding them to functions.
func LoadCommands() map[string]Command {
	return map[string]Command{
		"verify": {
			Function:        commandVerify,
			Source:          CommandSourcePRIVATE,
			Description:     "Verify you are the owner of a SA:MP forum account",
			Usage:           "verify",
			RequireVerified: false,
			RequireAdmin:    false,
		},
	}
}
```

Todo: a way for a command context to continue even after the command has been issued, so until the context has been declared finished, extra messages can contain any text and will be sent to the context of the command.

The use case for this is to implement the command framework but still allow users to submit arbitrary text for the "provide user account URL" stage of the verification process.

**Comment by Southclaws** [comment]
Now working on this in [command-framework](https://github.com/Southclaws/cj/tree/command-framework).

**Comment by WopsS** [comment]
Should we close this?
