### ISSUE TITLE
No description found

### ISSUE THREAD

**Issue by traxyy** [Southclaws/cj#195]
I'm sure this is already noted but just to remind, when we use /wiki (what u want to search), it returns the func/callback name properly but it doesn't show the description. It only tells that description isn't found. Now if we try /wiki vehicle, suppose you get 2 functions:

1) createvehicle
2) addstaticvehicle

So, there will be no description for the first one. However if I do /wiki addstaticvehicle it won't show description for that function then(note that it was showing the description when it was showed on 2nd number and not first!)

I'm no genius but this bug only seems to occur for the first func/callback displayed (iirc)

EDIT: just did some more /wiki tests and this doesn't happen for every searched callback/func

**Comment by coool9** [comment]
I did some research on this. I believe that this is due to open.mp API.

**Comment by coool9** [comment]
isn't this fixed?

**Comment by Southclaws** [comment]
Some pages don't provide a description. This is a data issue rather than a code issue.
