### ISSUE TITLE
Command for wiki searches

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#20]
> Hey man, I did a suggestion for CJ bot but idk if you saw it.
> The suggestion is create a /wiki command and make the bot return a link to http://wiki.sa-mp.com/wiki/Parameter
> E.g.:
> (user command)
> /wiki onplayerd
> 
> (bot messages, limit of matches is 3)
> NPC:OnPlayerDeath http://wiki.sa-mp.com/wiki/NPC:OnPlayerDeath
> OnPlayerDeath http://wiki.sa-mp.com/wiki/OnPlayerDeath
> OnPlayerDisconnect http://wiki.sa-mp.com/wiki/OnPlayerDisconnect
> 
> I did an example of how it should work (I know you can do it, I'm using it to learn Go by the first time!):
> https://gist.github.com/Renato-Garcia/97c62f4b55db3d2bcfceddbda87710d1

cc @Renato-Garcia

**Comment by WopsS** [comment]
Should we fetch the wiki for new pages when bot starts and every day at 00:00? We can keep them in database in a table named **wiki_pages**.

**Comment by Southclaws** [comment]
I was thinking of just doing a HTTP GET on the command parameter string, if it doesn't 404 then save the result URL in the cache and use the cache for future requests. I'm generally avoiding persistent storage as much as possible so the app is largely state-less besides user verifications.

**Comment by WopsS** [comment]
Ok, but what if someone type **/wiki onplayerd** as @Renato-Garcia says, we will be able to display what we have in cache. What I was saying is to fetch the wiki for all functions and store their name in database or cache and when a user request it, get it from database or from cache and then when a user request more details about a command do what you said.

**Comment by Crayder** [comment]
I agree with WopsS, we can cache the function and callback names to make things more convenient.

**Comment by Southclaws** [comment]
Search could just directly use the wiki search feature then scrape the results page:

http://wiki.sa-mp.com/wiki/Special:Search?search=querystring&go=Go
