### ISSUE TITLE
Limit parameters for /whois (and probably other commands)

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#21]
This could probably be tied into #18 as an option for commands, /whois would be a "variadic" command that takes between 1 and n parameters whereas /say would take exactly 1 parameter.

**Comment by WopsS** [comment]
We could implement a member as you did for usage message. If it is **-**  or **0** it will get all parameters as a string, else get just first **n** parameters.

**Comment by Southclaws** [comment]
Yes that makes sense, I can imagine a lot of these commands having an arbitrary amount of arguments (lists of users, etc) so sticking a number onto the command object could work.

**Comment by WopsS** [comment]
Implemented in b46cd8b.
