### ISSUE TITLE
Problem with /userinfo command

### ISSUE THREAD

**Issue by WopsS** [Southclaws/cj#26]
When a user has more than 1000 posts it will fail to convert it to an integer because the comma.

@Southclaws's profile:
* **Join Date**: Apr 2009
* **Total Posts**: 4,637
* **Reputation**: 1204

What **CJ** return when someone execute **/userinfo**:
> Username: [HLF]Southclaw Member since: 22/04/2009 Total posts: 0 Reputation: 1204

**Comment by WopsS** [comment]
The problem is here https://github.com/Southclaws/cj/blob/master/bot_forums.go#L110-L113

**Comment by Southclaws** [comment]
Should be as easy as just stripping out comma characters.

**Comment by WopsS** [comment]
We can keep it to look nice.
