### ISSUE TITLE
Add "whois" command to check forum username of discord user

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#4]
`/whois @Southclaws` > "[HLF]Southclaw"
`/whois @UnverifiedUser` > "That user is not verified"

**Comment by WopsS** [comment]
I can see two options to handle this command:

1. In a private message.
2. On the primary channel for the bot.

Where should this be implemented? I think it should be implemented on the primary channel for the bot or to handle commands sent in all channels.

**Comment by Southclaws** [comment]
Yeah I thought the primary channel would make sense, that's where discussion happens and it's usually a group of people in conversation who want to know the identity of a user.

**Comment by WopsS** [comment]
Maybe we should add the link to user profile when bot respond to the command.
> **User** is **User** (**link**) on SA-MP forums.
