### ISSUE TITLE
Command for checking a user's forum stats

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/cj#8]
Requires some xpath/web scraping knowledge:

- Forum post count
- Forum reputation
- Total visitor messages
- Anything else interesting about a user on the forum that can be retrieved using the user's ID (mine is 50199 for example, you can access my profile page, all posts, all threads, posts-per-day, etc.)

**Comment by WopsS** [comment]
What do you say about **/userinfo** for this command?

We can use some parameters, like **general** (will include post count, reputation, posts-per-day), **visitor_messages**, what  do you say?

**Comment by Southclaws** [comment]
Yep, that sounds perfect!

**Comment by Crayder** [comment]
```
Discord Name: bleh
Forum Name: bleh
Online: (green, yellow, red)
Forum Join Date:
Discord Join Date:
Last Discord Activity (time and channel): bleh
Last Forum Activity (time and the last "Current Activity"): bleh
Total Posts: bleh
Reputation:
etc 
```

**Comment by Southclaws** [comment]
I don't think we need a Discord username (the user already knows this from typing the command), online status or some of the activity stuff.

I'd actually like to keep this minimal - even though there will be usage limiting to prevent spam, it's not really good practice to have commands post paragraphs of text. I say we post the info in a single paragraph but separate `keys` from `values` using formatting:

*Forum name:* **[HLF]Southclaw** *Member since:* **2009** *Reputation:* **1500** *etc:* **etc...**

Regarding the activity/date stuff: For one thing, most of the discord join dates are going to be early 2017, when this server opened. The forum join date is probably the more interesting one to users. Discord activity *could* be useful if a user disappears for a while, depends if the API exposes this value as I'd rather not introduce more state tracking to the bot. Last forum activity can be scraped but is it really necessary? Use cases?

**Comment by JohnyMac** [comment]
I've added scraping for TotalPosts, LastActive and JoinDate... Reputation is remaining though which I don't know where should I get it from. I need to goto any of user's posts to get it or any other solution ?
https://github.com/JohnyMac/cj/commit/406486116d894e2d59955ff664dbe17c261930b3

**Comment by Southclaws** [comment]
It should be visible from the user profile page, in the "mini stats" box if I remember correctly.

**Comment by JohnyMac** [comment]
It doesn't..

**Comment by Crayder** [comment]
>I don't think we need a Discord username (the user already knows this from typing the command), online status or some of the activity stuff.

- Discord username: People can have multiple names. Like khanz for example, his real Discord name is aymel (not talking about his forum name). We should show this.
- Online status: Agreed, not needed.
- Activity stuff: I think both, forum and discord activity would be useful.

As I suggested to @JohnyMac, maybe we should separate the discord/forum data. 

`/info <user>`
```
Name(s): (and aka's, see below)
Join Date: (date joined Discord)
Last Activity: ("time in #channel" or "Online in #channel")
```
`/forum <user>`
```
Name: (current forum name)
Join Date:
Last Activity:  (time and the last "Current Activity" from the forum... ex. [was viewing Bleh Bleh Bleh on data/time])
Posts: 
Reputation:
```

------------------

Also, when you PM people with multiple names you can see their alternative names at the top, is it possible to get these AKA's through the API?

**Comment by JohnyMac** [comment]
Command should be in pm or general channel ?
And also @Crayder there is no a last activity thing, but only current activity...

**Comment by Southclaws** [comment]
I say general, but with rate-limiting and a minimal line-footprint (see my earlier post).
We could add a separate command for listing Discord names: `/aliases` or it could be integrated into this one.

**Comment by WopsS** [comment]
An idea for this command is to store reputation in a database field and a MD5 hash for page http://forum.sa-mp.com/search.php?do=finduser&u=ID and every time when a user execute this command to compare the MD5 or they will wait a little bit for the bot to query 2 pages.

**Comment by JohnyMac** [comment]
That hash will be different everytime the user posts and not when rep changes.
I think just adding a cooldown or something to make it only accept new request after previous is done would be good.

**Comment by Southclaws** [comment]
The codebase has a cache available at `app.cache`, it uses [patrickmn/go-cache](https://github.com/patrickmn/go-cache) and supports expiry.

So just store the user profile object or data in a cache keyed by the ID/URL/Username and only do lookups if the cache lookup doesn't hit.

**Comment by Crayder** [comment]
>And also @Crayder there is no a last activity thing, but only current activity...

Yes, like I literally said, it's called "Current Activity" on the forum. It's only available when the user is active on the forum. So we will only show that line if the user is online on the forum. And yes, CJ should call it "Last Activity" since it's sent in a message that isn't current after it's sent.
